# action is where the schedule is defined
# (scripts can be run manually, or by whatever automation calls them - it doesn't care about schedule)


on:
  schedule:
  - cron: 0 0 * * 1

jobs:
  workhorse:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
    - run: ./scripts/install
    - run: ./scripts/run ci plan label-automerge
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    # - uses: dropseed/workhorse@v1
    #   with:
    #     script: relabel-automerge
    #     github_token: ${{ secrets.GITHUB_TOKEN }}

        # workhorse plan $SCRIPT
        # new
          # commit
          # push and open PR
        # exists (workhorse/scriptpath without extension and lowercase, prepend with workhorse/ if it doesn't have it? or ask them to specify branch name for now?)
          # rebase? remove old plan/update it
          # update PR title and body
